language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - script/setup
  - pip install tensorflow  # this is so Keras loads for the tests

script:
  - script/test

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      script/distribute;
    fi
