version: 2
jobs:
  build:
    working_directory: ~/keras-tools
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
            - ".cache"
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          command: |
            . venv/bin/activate
            script/up
      - run:
          command: |
            . venv/bin/activate
            script/test