version: '3'
services:
  inception_serving:
    image: snormore/tensorflow-serving
    volumes:
      - .cache/models/tf/inception_v3:/model/1
    ports:
      - "9001:9000"
    command: "tensorflow_model_server --port=9000 --model_name=inception --model_base_path=/model"
  mobilenet_serving:
    image: snormore/tensorflow-serving
    volumes:
      - .cache/models/tf/mobilenet:/model/1
    ports:
      - "9002:9000"
    command: "tensorflow_model_server --port=9000 --model_name=mobilenet --model_base_path=/model"
  resnet50_serving:
    image: snormore/tensorflow-serving
    volumes:
      - .cache/models/tf/resnet50:/model/1
    ports:
      - "9003:9000"
    command: "tensorflow_model_server --port=9000 --model_name=resnet50 --model_base_path=/model"
  xception_serving:
    image: snormore/tensorflow-serving
    volumes:
      - .cache/models/tf/xception:/model/1
    ports:
      - "9004:9000"
    command: "tensorflow_model_server --port=9000 --model_name=xception --model_base_path=/model"