version: '3'
services:
  inception_v3:
    image: snormore/tensorflow-serving-base
    volumes:
      - .cache/models/inception:/model/1
    ports:
      - "9001:9000"
  mobilenet_v1:
    image: snormore/tensorflow-serving-base
    volumes:
      - .cache/models/mobilenet:/model/1
    ports:
      - "9002:9000"
  resnet50:
    image: snormore/tensorflow-serving-base
    volumes:
      - .cache/models/resnet50:/model/1
    ports:
      - "9003:9000"
  xception:
    image: snormore/tensorflow-serving-base
    volumes:
      - .cache/models/xception:/model/1
    ports:
      - "9004:9000"
  vgg16:
    image: snormore/tensorflow-serving-base
    volumes:
      - .cache/models/vgg16:/model/1
    ports:
      - "9005:9000"
  vgg19:
    image: snormore/tensorflow-serving-base
    volumes:
      - .cache/models/vgg19:/model/1
    ports:
      - "9006:9000"